### ISSUE TITLE
Improvements in BlenderBIM integration

### ISSUE THREAD

**Issue by Moult** [kevancress/MeasureIt-ARCH#110]
So we have a thing :)

![image](https://user-images.githubusercontent.com/88302/89178674-7a99c380-d5d1-11ea-81fb-55ddcb199d34.png)

Would it be possible for https://github.com/kevancress/MeasureIt-ARCH/blob/master/measureit_arch_external_utils.py#L30 to return the actual offset locations, otherwise they appear exactly on vertices as shown?

Also returning the coord list might be nice :) https://github.com/kevancress/MeasureIt-ARCH/blob/master/measureit_arch_external_utils.py#L81

**Comment by kevancress** [comment]
Hey @Moult, Sorry about the slow reply, I've been off in the woods without an internet connection for the last week!

commit f58ba270dac08b8b37cd794db5e5bc849e37257d now returns the coord list (sorry that was silly of me to just print it ) and adds an optional argument offset_pos (true by default) to specify that the function should return the start and end points of the dimension line rather than the anchor points.

I'll try and clean this up and generalize it to all of the dimension types this week too!

**Comment by Moult** [comment]
Hmm, I added a dim to a wall with a solidify modifier (5.90m in the screenshot) and it returned an empty list.

Then I added a cube with a 2m dimension, and I got an exception:

![2020-08-12-131244_1920x1080_scrot](https://user-images.githubusercontent.com/88302/89971063-940bd100-dc9d-11ea-87c7-ffe82cca6c97.png)

**Comment by kevancress** [comment]
Ahh, right, sorry some of my drawing code makes the assumption that it's always occurring in the context of a 3D viewport, which I suppose isn't the case when it's being called externally.

Should be fixed in 88fa4920ff9911e0dbc93dcba50240b532c07efb, there does need to be a 3D viewport open somewhere in the blender workspace, but as long as one is present there should be no issue

![image](https://user-images.githubusercontent.com/16860574/90051616-f072ee80-dca5-11ea-802f-339c71269539.png)

**Comment by Moult** [comment]
Hmm, the dimensions still don't seem to be offset: 
![image](https://user-images.githubusercontent.com/88302/90078056-0a184280-dd47-11ea-9dc1-4e2eca68b0c3.png)

I call it in my script like so:

```
    def draw_measureit_arch_dimension_annotations(self):
        try:
            import MeasureIt_ARCH.measureit_arch_external_utils
            coords = MeasureIt_ARCH.measureit_arch_external_utils.blenderBIM_get_coords(bpy.context)
        except:
            return
        for coord in coords:
            self.draw_dimension_annotation(Vector(coord[0]), Vector(coord[1]))
```

When calling it in my script in the operator, I get these coords printed:

```
[[Vector((-1.0, 1.0, 1.0)), Vector((1.0, 1.0, 1.0))], [Vector((1.0, -1.0, 1.0)), Vector((1.0, 1.0, 1.0))]
```

As you can see, they are coincident with the verts of the default cube.

However, if I call it within the Python console, then indeed I get the offset coordinates:

```
>>> MeasureIt_ARCH.measureit_arch_external_utils.blenderBIM_get_coords(C)
[[Vector((-1.0, 1.5, 1.0)), Vector((1.0, 1.5, 1.0))], [Vector((1.5, -1.0, 1.0)), Vector((1.5, 1.0, 1.0))]]
[[Vector((-1.0, 1.5, 1.0)), Vector((1.0, 1.5, 1.0))], [Vector((1.5, -1.0, 1.0)), Vector((1.5, 1.0, 1.0))]]
```

I don't understand why the discrepancy?

An additional issue, perhaps unrelated, is that I get coordinates for aligned dims, but not axis dims.

**Comment by kevancress** [comment]
hmm, there's an optional argument 'offset_pos' that should be true by default, but it might fix things if you set it to true explicitly?
` coords = MeasureIt_ARCH.measureit_arch_external_utils.blenderBIM_get_coords(bpy.context, offset_pos = True)` might do it. I'll look into it further though.

And yep right now I've only got this set up for aligned Dims. I'll try and get it set up for the other types soon.
